### ISSUE TITLE
Add continous test integration task

### ISSUE THREAD

**Issue by Fabryprog** [iotexproject/iotex-antenna-java#1]
Using command

```
man clean test 
```

**Comment by FeirenK** [comment]
Maybe   "mvn clean test" ?

**Comment by Fabryprog** [comment]
Sure!  It was a phone type typo 😂

**Comment by Fabryprog** [comment]
@FeirenK where is the continous test dashboard? Can you give me the url?

**Comment by FeirenK** [comment]
@Fabryprog  my circleci:  https://circleci.com/gh/FeirenK/iotex-antenna-java/1 .  You can login to add this project

**Comment by Fabryprog** [comment]
@raullenchai can you insert this project into iotextproject circleci account? 

tnkx
