### ISSUE TITLE
How do convert an ETH address to an IOTX address

### ISSUE THREAD

**Issue by leezijie** [iotexproject/iotex-antenna-java#23]
How do convert an ETH address to an IOTX address

**Comment by leezijie** [comment]
public static String convertToIotxAddress(String ethAddr) {
        byte[] bytes = Numeric.hexStringToByteArray(ethAddr);
        byte[] words = Bech32.convertBits(bytes, 0, bytes.length, 8, 5, true);
        return IotxBech32.encode(AddressPrefix, words);
    }

**Comment by 1029219814** [comment]
> public static String convertToIotxAddress(String ethAddr) { byte[] bytes = Numeric.hexStringToByteArray(ethAddr); byte[] words = Bech32.convertBits(bytes, 0, bytes.length, 8, 5, true); return Bech32.encode(AddressPrefix, words); }

The address transferred using this method is different from what the browser sees
