### ISSUE TITLE
Refactor Suggestions

### ISSUE THREAD

**Issue by ququzone** [iotexproject/iotex-antenna-java#9]
1. Project now only has generated grcp codes and a simple client IoTeXDispatcher class

2. Our base code structure should consistent with [iotex-antenna](https://github.com/iotexproject/iotex-antenna) and [iotex-antenna-go](https://github.com/iotexproject/iotex-antenna-go), so first step we should add rpcmethod package replace IoTeXDispatcher.java

3. GRPC generate code should only have generated code, don't put other code in that package

4. We can continue implement transfer, contract base on rpcmethod package

**Comment by Fabryprog** [comment]
done!

**Comment by Fabryprog** [comment]
(point 4 will be resolve into separated issue!)
